[package]
name = "kovi-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
kovi.workspace = true
kovi-milky.workspace = true
kovi-plugin-cmd = { version = "0.4.0", features = ["milky"] }
message-reaction = { version = "0.1.0", path = "plugins/message-reaction" }
emoji-manager = { version = "0.1.0", path = "plugins/emoji-manager" }

[workspace]
members = ["plugins/emoji-manager","plugins/message-reaction"]

[workspace.dependencies]
kovi = "0.13.5"
kovi-milky = "0.13.5"
regex="1"
serde = { version = "1", features = ["derive"] }
